# Default configuration for PiCar-X Robot
# Copy this file to production.yaml and modify as needed

hardware:
  # I2C configuration
  i2c_bus: 1
  
  # Servo configuration
  servo_pins:
    pan: 0  # Pan servo pin
    tilt: 1  # Tilt servo pin
  
  # Motor configuration
  motor_pins:
    left: 2  # Left motor pin
    right: 3  # Right motor pin
  
  # Ultrasonic sensor configuration
  ultrasonic_pins:
    trigger: 17  # GPIO pin for trigger
    echo: 27    # GPIO pin for echo
  
  # Camera configuration
  camera:
    enabled: true
    resolution: [640, 480]  # Width, Height
    framerate: 30
    rotation: 0  # Degrees (0, 90, 180, or 270)

system:
  # System monitoring
  monitoring:
    update_interval: 5  # Seconds between updates
    cpu_temp_path: "/sys/class/thermal/thermal_zone0/temp"
    battery_voltage_pin: 4  # ADC pin for battery reading
    history_size: 100  # Number of historical readings to keep
  
  # Logging configuration
  logging:
    level: "INFO"  # DEBUG, INFO, WARNING, ERROR, CRITICAL
    file: "robot.log"
    max_size: 10485760  # 10MB
    backup_count: 5

voice:
  # Voice recognition settings
  recognition:
    wake_word: "robot"
    audio_device_index: 1  # Use 'arecord -l' to find correct device
    language: "en-US"
    timeout: 5  # Seconds to listen for each command
  
  # Text-to-speech settings
  speech:
    rate: 150  # Words per minute
    volume: 0.8  # 0.0 to 1.0

navigation:
  # Movement parameters
  max_speed: 50  # Percentage of max motor speed
  turn_speed: 30  # Percentage of max motor speed during turns
  min_obstacle_distance: 20  # cm
  
  # Grid-based mapping
  mapping:
    grid_resolution: 5  # cm per grid cell
    max_grid_size: [1000, 1000]  # Width, Height in cm
    update_threshold: 0.7  # Probability threshold for marking cell as occupied
    unknown_value: 0.5  # Initial probability for unexplored cells

chatgpt:
  # ChatGPT API configuration
  api:
    model: "gpt-4"  # or "gpt-3.5-turbo"
    temperature: 0.7
    max_tokens: 150
    request_timeout: 10  # seconds
  
  # Rate limiting
  rate_limit:
    max_requests_per_minute: 20
    min_request_interval: 3  # seconds

web:
  # Web interface settings
  server:
    host: "0.0.0.0"
    port: 8080
    debug: false
  
  # WebSocket settings for real-time updates
  websocket:
    update_interval: 0.1  # seconds
    max_clients: 5

security:
  # Web interface authentication
  web_auth:
    enabled: true
    username: "admin"
    password: "changeme"  # Change this in production.yaml
  
  # API authentication
  api_auth:
    enabled: true
    token: ""  # Set this in production.yaml 